#!/usr/bin/env bash
set -euo pipefail

export LOGLEVEL=INFO
export HYDRA_FULL_ERROR=1
export TF_CPP_MIN_LOG_LEVEL=2
export PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True
export CUDA_VISIBLE_DEVICES="${CUDA_VISIBLE_DEVICES:-0,1,2,3,4,5,6,7}"

CONDA_ROOT="${CONDA_ROOT:-/root/anaconda3}"
CONDA_ENV="${CONDA_ENV:-trajtok}"
CACHE_ROOT="${CACHE_ROOT:-/mnt/pfs/waymo_motion_1_3_0/preprocessed_scenario}"
NUM_GPUS="${NUM_GPUS:-8}"
MY_EXPERIMENT="${MY_EXPERIMENT:-pre_bc}"
MY_TASK_NAME="${MY_TASK_NAME:-${MY_EXPERIMENT}_b200}"
WANDB_OFFLINE="${WANDB_OFFLINE:-true}"
WANDB_ENTITY="${WANDB_ENTITY:-null}"

if [[ ! -f "${CONDA_ROOT}/etc/profile.d/conda.sh" ]]; then
  echo "Conda initialization script not found: ${CONDA_ROOT}/etc/profile.d/conda.sh" >&2
  exit 1
fi

source "${CONDA_ROOT}/etc/profile.d/conda.sh"
conda activate "${CONDA_ENV}"

require_files() {
  local directory="$1"
  local pattern="$2"

  if [[ ! -d "${directory}" ]]; then
    echo "Required data directory not found: ${directory}" >&2
    exit 1
  fi

  if ! find "${directory}" -maxdepth 1 -type f -name "${pattern}" -print -quit | grep -q .; then
    echo "No ${pattern} files found in ${directory}" >&2
    echo "CACHE_ROOT must point to data generated by src.data_preprocess." >&2
    exit 1
  fi
}

require_files "${CACHE_ROOT}/training" "*.pkl"
require_files "${CACHE_ROOT}/validation" "*.pkl"
require_files "${CACHE_ROOT}/validation_tfrecords_splitted" "*.tfrecords"

AVAILABLE_GPUS="$(python -c 'import torch; print(torch.cuda.device_count())')"
if (( AVAILABLE_GPUS < NUM_GPUS )); then
  echo "Requested ${NUM_GPUS} GPUs, but PyTorch sees only ${AVAILABLE_GPUS}." >&2
  exit 1
fi

python -c 'import torch; x = torch.ones(1, device="cuda"); print(f"PyTorch {torch.__version__}, CUDA {torch.version.cuda}, GPU 0: {torch.cuda.get_device_name(0)}, architectures: {torch.cuda.get_arch_list()}")'

torchrun \
  --standalone \
  --nnodes=1 \
  --nproc_per_node="${NUM_GPUS}" \
  -m src.run \
  experiment="${MY_EXPERIMENT}" \
  trainer=ddp \
  paths.cache_root="${CACHE_ROOT}" \
  logger.wandb.offline="${WANDB_OFFLINE}" \
  logger.wandb.entity="${WANDB_ENTITY}" \
  task_name="${MY_TASK_NAME}" \
  "$@"

echo "CatK ${MY_EXPERIMENT} training completed."
